name: Slack Interactive Scoreboard
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      trigger_quiz:
        description: 'Do you want to trigger the quiz?'
        required: true
        default: 'yes'
      question:
        description: 'What is your question?'
        required: true
        default: 'What is the best way to deploy a Node.js app?'
jobs:
  validate-questions:
    runs-on: ubuntu-latest
    outputs:
      has_new_question: ${{ steps.check-questions.outputs.has_new_question }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Validate Questions
        id: check-questions
        run: |
          if grep -q "${{ inputs.question }}" questions.yml; then
            echo "Questions are valid"
            echo "has_new_question=true" >> $GITHUB_OUTPUT
          else
            echo "Questions are not valid"
            echo "has_new_question=false" >> $GITHUB_OUTPUT

  slack-interactive-manual:
    if: ${{ inputs.trigger_quiz }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
    
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: We have a new question! ${{ inputs.question }}
          SLACK_TITLE: Quiz
          SLACK_COLOR: good
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
  slack-interactive:
    if: needs.validate-questions.outputs.has_new_question == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Questions
        run: |
          QUESTION=$(shuf -n 1 ./questions.yml | cut -d '-' -f2-)
          echo "QUESTION=$QUESTION" >> $GITHUB_ENV
          echo $QUESTION
    
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: We have a new question! ${{ env.QUESTION }}
          SLACK_TITLE: Quiz
          SLACK_COLOR: good
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}