name: Slack Interactive Scoreboard
on:
  push:
    branches:
      - main
    paths:
      - 'questions.yml'
  workflow_dispatch:
    inputs:
      trigger_quiz:
        description: 'Do you want to trigger the quiz?'
        required: true
        default: 'yes'
      name:
        description: 'What is your name?'
        required: true
        default: 'Chris'
      question:
        description: 'What is your question?'
        required: true
        default: 'What is the best way to deploy a Node.js app?'
jobs:
  slack-interactive-manual:
    if: ${{ inputs.trigger_quiz }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
    
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: We have a new question! ${{ inputs.name }}: ${{ inputs.question }}
          SLACK_TITLE: Quiz
          SLACK_COLOR: good
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
  slack-interactive:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Questions
        run: |
          QUESTION=$(shuf -n 1 ./questions.yml | cut -d '-' -f2-)
          echo "QUESTION=$QUESTION" >> $GITHUB_ENV
          echo $QUESTION
    
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: We have a new question! ${{ env.QUESTION }}
          SLACK_TITLE: Quiz
          SLACK_COLOR: good
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}